# Generated by Django 4.0.6 on 2022-08-01 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('camper_id', models.IntegerField(primary_key=True, serialize=False)),
                ('camper_password', models.CharField(blank=True, max_length=100, null=True)),
                ('camper_email', models.CharField(blank=True, max_length=100, null=True)),
                ('camper_registrationdate', models.DateField(blank=True, null=True)),
                ('camper_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'camper',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('park_id', models.IntegerField(primary_key=True, serialize=False)),
                ('park_name', models.CharField(blank=True, max_length=100, null=True)),
                ('park_state', models.CharField(blank=True, max_length=20, null=True)),
                ('park_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('park_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('park_avgrating', models.FloatField(blank=True, null=True)),
                ('park_numreviews', models.IntegerField(blank=True, null=True)),
                ('park_sevendaycost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'park',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('camper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camper')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.park')),
            ],
            options={
                'db_table': 'review',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_startdate', models.DateField(blank=True, null=True)),
                ('reservation_enddate', models.DateField(blank=True, null=True)),
                ('reservation_totalcost', models.FloatField(blank=True, null=True)),
                ('camper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camper')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.park')),
            ],
            options={
                'db_table': 'reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.park')),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
    ]
